---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  labels:
    k8s-app: gitlab
  namespace: gitlab
spec:
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce:latest
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 443
          name: webssl
        - containerPort: 80
          name: web
        - containerPort: 22
          name: ssh
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 3
        volumeMounts:
        - mountPath: /etc/gitlab
          name: gitlab-etc
        - mountPath: /var/opt/gitlab
          name: gitlab-data
        - mountPath: /var/log/gitlab
          name: gitlab-logs
      volumes:
      - name: gitlab-etc
        persistentVolumeClaim:
          claimName: gitlab-etc
      - name: gitlab-data
        persistentVolumeClaim:
          claimName: gitlab-data
      - name: gitlab-logs
        persistentVolumeClaim:
          claimName: gitlab-logs