---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-pvc-etc
  labels:
    k8s-app: gitlab
    type: local
  namespace: gitlab
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-pvc-data
  labels:
    k8s-app: gitlab
    type: local
  namespace: gitlab
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-pvc-logs
  labels:
    k8s-app: gitlab
    type: local
  namespace: gitlab
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---